language: node_js
node_js:
- '8.10'
install: npm install
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy -- -v --stage dev
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: npm run deploy -- -v --stage prod
  on:
    branch: master
